swagger:
  contact:
    name: Anderson Sales
    email: anderson.luiz.sales@gmail.com
  app:
    name: Telephonebook API
    version: 0.0.1
    description: API responsável por gerenciar crud de uma agenda telefonica.
  base:
    package: br.com.telephonebook.telephonebookapi

spring:
  data:
    mongodb:
      host: db
      port: 27017
      database: telephonebook-api

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: null
      path-mapping:
        health: /healthcheck

openfeign:
  url:
    hg-brasil-api: ${OPENFEIGN_URL_HGBRASILAPI}

logging:
  level:
    br:
      com:
        hg:
          hgbrasilapi:
            clients:
              HgClientBrasil: DEBUG